version: '3.8'
services:
  web:
    image: weather_app
    build:
      context: /home/biba/petProj
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - /home/biba/petProj:/app