name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: [self-hosted, Linux, X64 ]

    steps:
    - name: Pull Docker Image
      run: sudo docker pull shinratttensei/petproject:latest

    - name: Setting Environment Variables
      env:
        API_KEY: ${{ secrets.WEATHER_API_KEY }}

      run: echo "API_KEY=$API_KEY" >> $GITHUB_ENV

    - name: Delete the Old docker container
      run: docker rm -f petproject-container || true

    - name: Run Docker Container
      run: docker run -d -p 5000:5000 --name petproject-container -e API_KEY=${{ secrets.API_KEY }} shinratttensei/petproject


